apiVersion: v1
kind: Service
metadata:
  name: shadowsocks-service
  labels:
    name: shadowsocks
spec:
  selector:
    name: shadowsocks 
  type: NodePort
  ports:
   - protocol: TCP
     port: 8288
     targetPort: 8388
     nodePort: 30001
  
